### ISSUE TITLE
LDP Remote Peer

### ISSUE THREAD

**Issue by saman-com** [braincan/cienasaos10ncc#1]
Hi,
I have add following def to the code:

```
	def create_ldp_remote(self, tag: "str", peer_ip: "str") -> bool:
		""" Create a remote ldp peer on SAOS10

		:param name: The name of the forwarding domain
		:param description: The description of the forwarding domain
		:param mode: One of the following (evpn-vpls, evpn-vpws, fxc, tdm-vpws, vlan, vpls, vpws)
		:return Will return True on Success and False on Failure.
		"""
		ldp_r_template = self.env.get_template("ldp_remote.xml")
		ldp_r_rendered = ldp_r_template.render(
			FD_DELETE=False,
			INSTANCE_TAG=tag,
			PEER_IP=peer_ip
		)
		print (ldp_r_rendered)
		rpc_reply = self.device.edit_config(target="running", config=ldp_r_rendered, default_operation = "merge")
		# if not self._check_response(rpc_reply, "CREATE_FORWARDING_DOMAIN"):
		# 	return False
		return True
```

also I add follwing xml file:

```
<config>
	<ldp xmlns="http://ciena.com/ns/yang/ciena/ciena-ldp">
        {%- if OPERATION_DELETE -%}
        <instance operation="delete">
        <tag> {{ INSTANCE_TAG }}</tag>
        </instance>
        {%- else -%}
        <instance>
			<tag>{{ INSTANCE_TAG }}</tag>
			<target-ldp>	
                <peers>{{ PEER_IP }}</peers>
			</target-ldp>
		</instance>
        {%- endif %}
	</ldp>
</config>
```

when I am calling this fuction to test. I am geeting this error:

```
python ciena_init.py 
<config>
        <ldp xmlns="http://ciena.com/ns/yang/ciena/ciena-ldp"><instance>
                        <tag>default</tag>
                        <target-ldp>
                <peers>10.10.10.100</peers>
                        </target-ldp>
                </instance>
        </ldp>
</config>
Traceback (most recent call last):
  File "ciena_init.py", line 10, in <module>
    test.create_ldp_remote ('default', '10.10.10.100')
  File "/home/saadzads/ciena_ncc_dev/cienasaos10ncc/cienasaos10ncc/saos10_netconf.py", line 621, in create_ldp_remote
    rpc_reply = self.device.edit_config(target="running", config=ldp_r_rendered, default_operation = "merge")
  File "/home/saadzads/ciena_ncc_dev/env/lib/python3.7/site-packages/ncclient/manager.py", line 251, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/saadzads/ciena_ncc_dev/env/lib/python3.7/site-packages/ncclient/operations/edit.py", line 76, in request
    return self._request(node)
  File "/home/saadzads/ciena_ncc_dev/env/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 375, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: expecting complex node type
```

if you can help it is really apreciated.

**Comment by saman-com** [comment]
I found the issue this is correct xmls file: 

```
<config>
	<ldp xmlns="http://ciena.com/ns/yang/ciena/ciena-ldp">
        {%- if LDP_DELETE -%}
        <instance operation="delete">
        <tag> {{ INSTANCE_TAG }}</tag>
        </instance>
        {%- else -%}
        <instance>
			<tag>{{ INSTANCE_TAG }}</tag>
			<target-ldp>	
                <peers>
                    <address>{{ PEER_IP }}</address>
                </peers>
			</target-ldp>
		</instance>
        {%- endif %}
	</ldp>
</config>
```

**Comment by lucasw-eng** [comment]
Nice find! Tracking down the specific YANG models can be such a pain. The best place to find them is typically the official Ciena documentation. If you end up adding significant code feel free to open a PR. 

Happy coding!
